name: ros_package_build

on:

  push:
    branches: [ master ]

    # paths-ignore:
    #   - '**/README.md'
    #   - '**.jpg'
    #   - '**.png'

  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:

  build:
    uses: jesusBV20/source_seeking/.github/workflows/ci.yml@master
    secrets:
      PUSH_TOKEN: ${{ secrets.PUSH_TOKEN }}